@startuml

class CareTaker {
	-memento : EmpMemento
	+setMemento(emt:EmpMemento) : void
	+getMemento() : EmpMemento
}

class Emp {
	-ename : String
	-age : int
	-salary : double
	+Emp(ename:String, age:int, salary:double)
	+toString() : String
	+setAge(age:int) : void
	+setEname(ename:String) : void
	+recovery(emt:EmpMemento) : void
	+getEname() : String
	+getAge() : int
	+getSalary() : double
	+memento() : EmpMemento
	+setSalary(salary:double) : void
}

class EmpMemento {
	-ename : String
	-age : int
	-salary : double
	+EmpMemento(emp:Emp)
	+setAge(age:int) : void
	+setEname(ename:String) : void
	+setSalary(salary:double) : void
	+getEname() : String
	+getAge() : int
	+getSalary() : double
}

Emp .right.> EmpMemento
CareTaker o-left-> EmpMemento

@enduml
