@startuml

interface State {
    handle() : void
}

class FreeState implements State {
    handle() : void
}

class CheckedState implements State {
    handle() : void
}

class BookedState implements State {
    handle() : void
}

class RoomContext {
    setState(State s) : void
}

class Client

RoomContext o-> State
Client ---> RoomContext

@enduml